//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClaimHead
    {
        public ClaimHead()
        {
            this.ClaimLines = new HashSet<ClaimLine>();
        }
    
        public int id { get; set; }
        public int EmpId { get; set; }
        public string ClaimNumber { get; set; }
        public string ClaimTitle { get; set; }
        public int Status { get; set; }
    
        public virtual ClaimStatu ClaimStatu { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual ICollection<ClaimLine> ClaimLines { get; set; }
    }
}
