//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;
    using Admin.Models;
    using System.Linq;

    public partial class EmpStatu
    {
        public EmpStatu()
        {
            this.Employees = new HashSet<Employee>();
        }
    
        public int EmpStatusId { get; set; }
        public string StatusName { get; set; }

        //public List<SelectListItem> getAllStatusesList { get; set; }
        //public List<SelectListItem> getAllList()
        //{
        //    List<SelectListItem> items = new List<SelectListItem>();
            
        //    ubietydbEntities dbcontext = new ubietydbEntities();

        //    using (var context = new ubietydbEntities())
        //    {
        //        // Query for all blogs with names starting with B 
        //        var allRows = from b in context.EmpStatus
        //                      select b;

        //        foreach (var result in allRows)
        //        {
        //            items.Add(new SelectListItem { Text = result.EmpStatusId.ToString(), Value = result.StatusName });
        //        }

        //        return items;
        //    }
        //}

        public IEnumerable<SelectListItem> EmpStatuses { get; set; }

        public virtual ICollection<Employee> Employees { get; set; }
    }
}
