//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UbietyAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.Attendances = new HashSet<Attendance>();
        }
    
        public int EmpId { get; set; }
        public string EmpNum { get; set; }
        public string EmpName { get; set; }
        public string ProfilePic { get; set; }
        public int EmpStatus { get; set; }
        public Nullable<int> ClientId { get; set; }
        public string Email { get; set; }
        public Nullable<long> PrimaryMobile { get; set; }
    
        public virtual ICollection<Attendance> Attendances { get; set; }
        public virtual EmpStatu EmpStatu { get; set; }
        public virtual Login Login { get; set; }
    }
}
